# from https://til.simonwillison.net/docker/emulate-s390x-with-qemu
# before running this docker, you need to set up QEMU for s390x emulation on your host machine. You can do this by running:
# docker run --rm --privileged multiarch/qemu-user-static --reset


# Use an explicit s390x Ubuntu base image
FROM --platform=linux/s390x ubuntu:latest

# check machine architecture
RUN uname -m

# Install necessary tools to build OpenJPH
RUN apt-get -y update
RUN apt-get -y install cmake
RUN apt-get -y install g++
RUN apt-get -y install libtiff-dev

# build OpenJPH
COPY . /usr/src/OpenJPH
WORKDIR /usr/src/OpenJPH/build
RUN rm -R * || true 
RUN cmake -DCMAKE_BUILD_TYPE=Release -DOJPH_BUILD_TESTS=ON ..
RUN make
RUN make install
ENV LD_LIBRARY_PATH=/usr/local/lib

# to run this docker in Ubuntu or WSL do the following steps:
# 1 - install QEMU in ubuntu
# sudo apt install qemu-user-static binfmt-support

# 2 - set special permissions for docker to use QEMU for s390x emulation 
# see from https://til.simonwillison.net/docker/emulate-s390x-with-qemu
# see https://oneuptime.com/blog/post/2026-02-08-how-to-fix-docker-exec-format-error-on-multi-platform-images/view
# sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

# 3a - make sure Docker Desktop on windows host if running docker from WSL Ubuntu
# 3b - Build the docker image
# sudo docker build -f Dockerfile_390x_big_endian -t s390x-ubuntu .

# 4a - run the docker (in isolated container)
# sudo docker run -it --rm s390x-ubuntu /bin/bash
# 4b - run the docker (mapping host directory /mnt/c/temp to container directory /tmp)
# sudo docker run -it --rm -v /mnt/c/temp:/tmp s390x-ubuntu /bin/bash

# to clear all existing docker images
# docker system prune -a

# docker in a docker for multi-platform builds
# see https://blog.devops.dev/how-to-install-qemu-for-multi-platform-builds-in-a-docker-in-docker-dind-container-83eae2590ac8
# docker run --privileged --rm tonistiigi/binfmt --install all


# to run using windows git bash terminal
# 1 - config QEMU: docker run --privileged --rm tonistiigi/binfmt --install all
# 2 - build s390x container using QEMU: docker build -f Dockerfile_390x_big_endian -t s390x-ubuntu .
# 3 - run s390x container using QEMU: docker run -it --rm -v /c/data/temp:/tmp s390x-ubuntu /bin/bash

# in WSL terminal
# sudo docker run --rm --platform linux/s390x alpine uname -m
# Unable to find image 'alpine:latest' locally
# latest: Pulling from library/alpine
# 13188190f2c5: Pull complete 
# 3ba62a63c44c: Download complete 
# 92e1b3a48a10: Download complete 
# Digest: sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
# Status: Image is up to date for alpine:latest
# s390x
